name: Robo de Atualizacao TechCompare

on:
  workflow_dispatch: # Permite rodar manualmente pelo bot√£o no GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Rodar script de atualizacao
        run: python atualizador.py

      - name: Salvar mudancas
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add script.js
          git commit -m "Automacao: Preco atualizado" || exit 0
          git push